// 'use client'

// import type { Metadata } from "next";
// import "./globals.css";
// import Header from "./Components/header";
// import Sidebar from "./Components/sidebar";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className="font-roboto"
//       >
//         <div className="flex">
//           <Sidebar />

//         </div>
//         {children}
//       </body>
//     </html>
//   );
// }


// src/app/layout.tsx
'use client'  // Keep this as a client component

import "./globals.css";
import Header from "./Components/header";
import Sidebar from "./Components/sidebar";
import Site from "./Components/dropdownSite";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-roboto">
        <div className="flex">
          <Sidebar />

          <div className="flex-grow">
            <Header title="Dashboard" />
            <Site />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
