// // 'use client'

// import Header from "./Components/header";
// import Sidebar from "./Components/sidebar";

// export default function Home() {
//   return (
//     // <div className="flex">
//     //   <Sidebar />
      
//     //   {/* HEADER */}
//     //   <div className="flex-grow">
//     //     {/* <div className="shadow-xl p-6 bg-white">
//     //       <span className="text-black font-bold text-xl">HOMEPAGE</span>
//     //     </div> */}
//     //     <Header title="Dashboard" />
//     //   </div>
//     // </div>
//     <h3>HALO</h3>
//   );
// }


// src/app/page.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomePage() {
  return (
    <div>
      <h1>Welcome to the Home Page</h1>
    </div>
  );
}
